<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEW8GLsR\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEW8GLsR/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEW8GLsR.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEW8GLsR\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEW8GLsR\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'EW8GLsR',
    'container.build_id' => '8c1c9921',
    'container.build_time' => 1526387076,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEW8GLsR');
