<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXMW2YIk\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXMW2YIk/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXMW2YIk.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXMW2YIk\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXMW2YIk\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XMW2YIk',
    'container.build_id' => 'ddd43d94',
    'container.build_time' => 1526052305,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXMW2YIk');
